[package]
name = "pomeg_editor_cli"
version = "0.1.0"
authors = ["Sage Hane <sage@sagehane.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpomeg = { version = "0.1.0", path = "libpomeg" }
clap = "2.33.3"

[workspace]
members = [
    "libpomeg",
]
